### ISSUE TITLE
GA Integration Disabled

### ISSUE THREAD

**Issue by daskarinam9** [levelten/intelligence-wp#4]
I'm trying to set up conversion tracking in Google Analytics for submitted contact forms. I downloaded the Gravity Forms Google Analytics Intelligence plugin and when I try to integrate with GA it says

"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In"

I have also tried to do this manually without the plugin but the conversions are not recording.

Any insight into this would be greatly appreciated!

**Comment by tomdude48** [comment]
I'm working on getting the app through Google's verification process. Hopefully, this will only take a few days. Still waiting to hear back.

**Comment by tomdude48** [comment]
Google approved that app. So it is working now.
